default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: cost_men_development

test:
  <<: *default
  database: cost_men_test
  # urlに全ての情報が含まれるため、他の情報は不要
  # url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
