import Head from "next/head";
import { PrimaryButton } from "../../components/button/PrimaryButton";
import { SuccessButton } from "../../components/button/SuccessButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>CostMen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div className=" text-4xl">Hello Next! Hello Vercel!</div>
        <PrimaryButton>Primary Button</PrimaryButton>
        <SuccessButton>Success Button</SuccessButton>
      </div>
    </>
  );
}
